CREATE TABLE LOCATION (
    ID INT NOT NULL,
    TITLE VARCHAR (100),
    SUBTITLE VARCHAR (150),
    POSTAL_CODE VARCHAR(5),
    PRIMARY KEY (ID)
);

CREATE TYPE ACCOMMODATION_TYPE AS ENUM ('ROOM', 'APARTMENT', 'MOBILE_HOME');

CREATE TABLE ACCOMMODATION (
    ID INT NOT NULL,
    TITLE VARCHAR (100),
    SUBTITLE VARCHAR (150),
    DESCRIPTION VARCHAR,
    TYPE ACCOMMODATION_TYPE,
    CATEGORIZATION INTEGER,
    PERSON_COUNT INTEGER,
    PRICE DECIMAL,
    IMAGE_URL VARCHAR,
    FREE_CANCELATION BOOLEAN,
    LOCATION_ID INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (ID)
);

CREATE TABLE USERS (
    ID INT NOT NULL,
    PRIMARY KEY (ID),
    FIRST_NAME VARCHAR (200),
    LAST_NAME VARCHAR (200),
    EMAIL VARCHAR
);

CREATE TYPE RESERVATION_TYPE AS ENUM ('PERMANENT','TEMPORARY', 'CANCELED');

CREATE TABLE RESERVATION (
    ID VARCHAR NOT NULL,
    PRIMARY KEY (ID),
    ACCOMMODATION_ID INT,
    TYPE RESERVATION_TYPE,
    USER_ID INT,
    CHECK_IN TIMESTAMP,
    CHECK_OUT TIMESTAMP,
    PERSONS_COUNT INT,
    SUBMITTED BOOLEAN,
    FOREIGN KEY (ACCOMMODATION_ID) REFERENCES ACCOMMODATION (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);


CREATE TABLE RESERVATION_HISTORY (
    ID INT NOT NULL,
    RESERVATION_ID VARCHAR,
    ENTRY_TIMESTAMP TIMESTAMP,
    FROM_TYPE RESERVATION_TYPE,
    TO_TYPE RESERVATION_TYPE,
    PRIMARY KEY (ID),
    FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION (ID)
);